# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-18 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_confirmstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
